{
  "formatVersion": "1.1",
  "component": {
    "group": "io.offerpro",
    "module": "offerpro-sdk",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "offerpro-sdk-2.0.1.aar",
          "url": "offerpro-sdk-2.0.1.aar",
          "size": 90672,
          "sha512": "1dc4a25b50951dd29fd68fcfb9115c7b261210cdf4a6081202c0145fa0a8c229b43234599a21ad24a4a74b7b910aa598b405c23d61ae87b1f4cce5631b5e2ce5",
          "sha256": "14c61893f52ec81aaaa543d08b0a0e2ef5eb187a550e68325572d8df49bc2623",
          "sha1": "3cc0c5b8270ae8a30c1873a8fd09dce03a6d3c2b",
          "md5": "eae33eab37b68cbecbff394b03338c65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "offerpro-sdk-2.0.1.aar",
          "url": "offerpro-sdk-2.0.1.aar",
          "size": 90672,
          "sha512": "1dc4a25b50951dd29fd68fcfb9115c7b261210cdf4a6081202c0145fa0a8c229b43234599a21ad24a4a74b7b910aa598b405c23d61ae87b1f4cce5631b5e2ce5",
          "sha256": "14c61893f52ec81aaaa543d08b0a0e2ef5eb187a550e68325572d8df49bc2623",
          "sha1": "3cc0c5b8270ae8a30c1873a8fd09dce03a6d3c2b",
          "md5": "eae33eab37b68cbecbff394b03338c65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "offerpro-sdk-2.0.1-sources.jar",
          "url": "offerpro-sdk-2.0.1-sources.jar",
          "size": 17029,
          "sha512": "20659c17c3aa11217daba51b92449ea9b870a998a423b384767b5a3f4fc2fecf8b64ee9b7d5f950645dbf4b3e77245b266460a8c81d8aced32d4301732f265a6",
          "sha256": "904298ea84cb26f6b03fed2030403ce9a837c0322c5189275efca270aeb14ca4",
          "sha1": "ca0646c1cc0915af24d6bd2fb87ce007e79abd68",
          "md5": "36c69950520287c9ed74d397a181a5e6"
        }
      ]
    }
  ]
}
